# Generated by Django 3.2.6 on 2021-09-10 13:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studyblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description_01', models.TextField(blank=True)),
                ('description_02', models.TextField(blank=True)),
                ('image_01', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('image_02', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('image_03', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('image_04', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('is_published', models.BooleanField(default=False)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='author.author')),
            ],
        ),
    ]
